### ISSUE TITLE
FR: Custom HTTP base path

### ISSUE THREAD

**Issue by Knud3** [grafana/carbon-relay-ng#543]
Add support for custom HTTP base path.

I tried Docker Hub release with nginx ingress and rewrite, but it failed partially.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /carbon(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: carbon-relay-ng
            port:
              name: http
```

https://example.com/carbon

![Screenshot from 2023-09-22 14-48-26](https://github.com/grafana/carbon-relay-ng/assets/62902464/f6f5bdcb-883b-4e27-87fe-8dedb8132728)
